quarkus:
  hibernate-orm:
    database:
      generation:
        ~: drop-and-create
  datasource:
    db-kind: postgresql
    username: payment_service_adm
    password: WJvlcsKMGdTDl0lWAwclEX6LFtyfQwfg
    jdbc:
      url: jdbc:postgresql://localhost:5432/walloliveira?currentSchema=payment_service_sch
  flyway:
    repair-at-start: true
encrypt:
  key: 0f7de5a2e21f6d0b82fd739d37b927d4
pagseguro:
  token: EC7C6842FD9E4D98931A5E04B8B06005